#!/bin/sh

bg_color=#dd2f343f
text_color=#f3f4f5
htext_color=#9575cd

rofi -show run -lines 3 -eh 2 -width 100 -padding 550 -bw 0 -color-window "$bg_color, $bg_color, #00000000" -color-normal "#00000000, $text_color, #00000000, #00000000, $htext_color" -font "System San Francisco Display 16"
